timeout: 400
driver:
  login_url: 'https://console.aws.amazon.com/'
  type: mozilla
  path: 'E:/WebDrivers/geckodriver.exe'
  headless: False
  profile: "C:/Users/narag/AppData/Roaming/Mozilla/Firefox/Profiles/wwaaewc8.default-release"
submissions:
  race1:
    link: "https://console.aws.amazon.com/deepracer/home?region=us-east-1#league/arn%3Aaws%3Adeepracer%3A%3A%3Aleaderboard%2F3f4f0e17-37eb-4363-bb9a-3bf1eafdc96b"
    model: 
      - "rogue-a-pro-17-OA"